name = "digital-me-ingest"
main = "src/index.js"
compatibility_date = "2026-06-20"


[[d1_databases]]
binding = "DB"
database_name = "digital-me-db"
database_id = "15d5fc67-60bf-4376-8706-b57bafb1e6d5"
